name: Deploy Nx Apps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"

      - name: Install dependencies
        run: bun install

      - name: Check Hostname Availability
        run: |
          if ! command -v hostname &> /dev/null; then
            echo "hostname could not be found"
            sudo apt-get update && sudo apt-get install -y hostname
          else
            hostname
          fi

      - name: Build and deploy both apps concurrently
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          bun add concurrently
          concurrently "bun run npx nx build individual-portal && vercel --token=$VERCEL_TOKEN --prod ./dist/apps/individual-portal" \
                      "bun run npx nx build admin-portal && vercel --token=$VERCEL_TOKEN --prod ./dist/apps/admin-portal \
                      "bun run npx nx build verisure-server && vercel --token=$VERCEL_TOKEN --prod ./dist/apps/verisure-server \"
