name: Deploy Nx Monorepo Apps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"

      - name: Install dependencies
        run: bun install

      - name: Build and deploy both apps concurrently
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} 
        run: |
          bun add concurrently
          concurrently "bun run nx build individual-portal && vercel --token=$VERCEL_TOKEN --prod ./dist/apps/individual-portal" \
                      "bun run nx build admin-portal && vercel --token=$VERCEL_TOKEN --prod ./dist/apps/admin-portal"
